/* oxlint-disable react(set-state-in-effect) -- API polling deliberately mirrors external state. */
import { useEffect, useState } from "react";
import { getWallets } from "@wallet-standard/app";
import { SolanaSignAndSendTransaction, SolanaSignMessage } from "@solana/wallet-standard-features";
import type { Wallet, WalletAccount } from "@wallet-standard/base";
import { v1 } from "../api/client";
import type { Opportunity } from "./Opportunities";
import { PublicNav } from "../components/PublicNav";

type Connected = { wallet: Wallet; account: WalletAccount; address: string };
type ConnectFeature = { connect: () => Promise<readonly WalletAccount[]> };
type MessageFeature = { signMessage: (input: { account: WalletAccount; message: Uint8Array }) => Promise<readonly { signature: Uint8Array }[]> };
type SendFeature = { signAndSendTransaction: (input: { account: WalletAccount; transaction: Uint8Array; chain: "solana:devnet"; options: { commitment: "finalized" } }) => Promise<readonly { signature: Uint8Array }[]> };
type Position = { package_id: string; round_pda: string; round_state: string; amount_lamports: number; tier: string; status: string; public_metadata?: { title?: string } };

function base64ToBytes(value: string) { return Uint8Array.from(atob(value), (character) => character.charCodeAt(0)); }
function base64(bytes: Uint8Array) { let value = ""; for (const byte of bytes) value += String.fromCharCode(byte); return btoa(value); }
function base58(bytes: Uint8Array) { const alphabet = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz"; const digits = [0]; for (const byte of bytes) { let carry = byte; for (let index = 0; index < digits.length; index += 1) { carry += digits[index] << 8; digits[index] = carry % 58; carry = Math.floor(carry / 58); } while (carry) { digits.push(carry % 58); carry = Math.floor(carry / 58); } } let result = ""; for (const byte of bytes) { if (byte !== 0) break; result += "1"; } for (let index = digits.length - 1; index >= 0; index -= 1) result += alphabet[digits[index]]; return result; }
function short(value: string) { return `${value.slice(0, 5)}…${value.slice(-5)}`; }
function compatibleWallets() { return getWallets().get().filter((wallet) => wallet.chains.includes("solana:devnet")); }

export function MyAccessPage() {
  const [wallets, setWallets] = useState<readonly Wallet[]>([]);
  const [connected, setConnected] = useState<Connected | null>(null);
  const [opportunities, setOpportunities] = useState<Opportunity[]>([]);
  const [positions, setPositions] = useState<Position[]>([]);
  const [entitlements, setEntitlements] = useState<Array<Record<string, unknown>>>([]);
  const [amounts, setAmounts] = useState<Record<string, string>>({});
  const [tier, setTier] = useState<"exclusive_early" | "delayed">("exclusive_early");
  const [notice, setNotice] = useState("Connect your existing Devnet wallet. QARAU never creates or stores a wallet for you.");
  const [busy, setBusy] = useState(false);

  const refreshPublic = () => { setWallets(compatibleWallets()); v1.opportunities().then((data) => setOpportunities(data.packages as unknown as Opportunity[])).catch(() => setNotice("Public research is temporarily unavailable.")); };
  const refreshPrivate = async () => { const [positionData, accessData] = await Promise.all([v1.auctionPositions(), v1.accessEntitlements()]); setPositions(positionData.positions as unknown as Position[]); setEntitlements(accessData.entitlements); };
  // This effect owns the public polling lifecycle; the setters intentionally mirror external API state.
  // oxlint-disable-next-line react(set-state-in-effect)
  useEffect(() => { refreshPublic(); const timer = window.setInterval(refreshPublic, 5_000); return () => window.clearInterval(timer); }, []);

  const authenticate = async (wallet: Wallet, account: WalletAccount) => { const signing = wallet.features[SolanaSignMessage] as MessageFeature | undefined; if (!signing) throw new Error("Wallet cannot sign messages."); const challenge = await v1.siwsChallenge(account.address); const signed = await signing.signMessage({ account, message: new TextEncoder().encode(challenge.message) }); if (!signed[0]?.signature) throw new Error("Wallet returned no signature."); await v1.siwsVerify({ address: account.address, nonce: challenge.nonce, signature: base64(signed[0].signature) }); setConnected({ wallet, account, address: account.address }); await refreshPrivate(); setNotice(`Authenticated as ${short(account.address)}.`); };
  const connect = async (wallet: Wallet) => { try { setBusy(true); const feature = wallet.features["standard:connect"] as ConnectFeature | undefined; if (!feature) throw new Error("Wallet cannot connect."); const accounts = await feature.connect(); const account = accounts.find((item) => item.chains.includes("solana:devnet")); if (!account) throw new Error("No Devnet account found in this wallet."); await authenticate(wallet, account); } catch (error) { setNotice(error instanceof Error ? error.message : "Wallet connection failed."); } finally { setBusy(false); } };
  const send = async (transactionBase64: string) => { if (!connected) throw new Error("Connect a wallet first."); const sender = connected.wallet.features[SolanaSignAndSendTransaction] as SendFeature | undefined; if (!sender) throw new Error("Wallet cannot send transactions."); const sent = await sender.signAndSendTransaction({ account: connected.account, transaction: base64ToBytes(transactionBase64), chain: "solana:devnet", options: { commitment: "finalized" } }); if (!sent[0]?.signature) throw new Error("Wallet returned no transaction signature."); return base58(sent[0].signature); };
  const bid = async (item: Opportunity) => { try { setBusy(true); const amount = Number(amounts[item.package_id] || item.access_round.minimum_bid_lamports); setNotice("Review and sign the escrowed bid in your wallet…"); const unsigned = await v1.bidTransaction(item.access_round_address, tier, amount); const signature = await send(unsigned.transaction_base64); await v1.confirmBid(item.access_round_address, signature); await refreshPrivate(); setNotice("Bid finalized on Devnet. Ranking is deterministic: amount, then time, then wallet address."); } catch (error) { setNotice(error instanceof Error ? error.message : "Bid failed."); } finally { setBusy(false); } };
  const claim = async (roundPda: string) => { try { setBusy(true); setNotice("Review the entitlement claim in your wallet…"); const unsigned = await v1.claimTransaction(roundPda); const signature = await send(unsigned.transaction_base64); const result = await v1.confirmEntitlement(roundPda, signature); await refreshPrivate(); setNotice(`Access finalized as ${short(result.entitlement_pda)}.`); } catch (error) { setNotice(error instanceof Error ? error.message : "Only a Top-N winner can claim access."); } finally { setBusy(false); } };
  const refund = async (roundPda: string) => { try { setBusy(true); setNotice("Review the full losing-bid refund in your wallet…"); const unsigned = await v1.refundTransaction(roundPda); await send(unsigned.transaction_base64); await refreshPrivate(); setNotice("Refund transaction finalized on Devnet."); } catch (error) { setNotice(error instanceof Error ? error.message : "Only a non-winning bid can be refunded."); } finally { setBusy(false); } };

  return <div className="public-research"><PublicNav /><main className="shell market-main">
    <section className="market-hero"><p className="meta">Existing wallet / Devnet</p><h1 className="display-sm">Bid for access. Claim only if you finish Top-N.</h1><p className="body market-lead">Your wallet signs every action. A bid is held by the program until settlement; winners claim a time-limited entitlement and non-winners recover the full bid.</p></section>
    <section className="market-state"><div><p className="meta">01 / Authenticate</p><h2 className="h2">{connected ? `Connected / ${short(connected.address)}` : wallets.length ? "Choose an existing wallet" : "No compatible wallet detected"}</h2></div><div><p className="body-sm">A message signature creates a wallet session. It costs no SOL and exposes no secret key.</p>{!connected && <div className="source-actions" style={{ marginTop: 18 }}>{wallets.map((wallet) => <button className="btn btn-primary" disabled={busy} key={wallet.name} onClick={() => connect(wallet)}>Connect {wallet.name}</button>)}</div>}</div></section>
    <section className="market-state"><div><p className="meta">02 / Active rounds</p><h2 className="h2">Validated research</h2><div className="source-actions" style={{ marginTop: 18 }}><button className={`opt ${tier === "exclusive_early" ? "is-active" : ""}`} onClick={() => setTier("exclusive_early")}>Early</button><button className={`opt ${tier === "delayed" ? "is-active" : ""}`} onClick={() => setTier("delayed")}>Delayed</button></div></div><div>{opportunities.map((item) => <article className="market-package" key={item.package_id}><p className="meta">{item.access_round.state.toUpperCase()} / Top {item.access_round.max_winners} / {item.access_round.bid_count} bids</p><h2 className="h2">{item.title}</h2><p className="body-sm">Minimum {item.access_round.minimum_bid_lamports.toLocaleString("en-US")} lamports · closes {new Date(item.access_round.closes_at).toLocaleString()}</p>{item.access_round.state === "live" && <div className="source-actions" style={{ marginTop: 16 }}><input className="input" inputMode="numeric" aria-label={`Bid for ${item.title}`} value={amounts[item.package_id] ?? String(item.access_round.minimum_bid_lamports)} onChange={(event) => setAmounts((current) => ({ ...current, [item.package_id]: event.target.value }))} /><button className="btn btn-primary" disabled={!connected || busy} onClick={() => bid(item)}>Place bid</button></div>}</article>)}{!opportunities.length && <p className="body-sm">No commitment-backed access rounds are published yet.</p>}</div></section>
    {connected && <section className="market-state"><div><p className="meta">03 / My positions</p><h2 className="h2">Bids and access</h2><p className="body-sm">{entitlements.length} active entitlement{entitlements.length === 1 ? "" : "s"}.</p></div><div>{positions.map((position) => <article className="market-package" key={`${position.round_pda}-${position.package_id}`}><p className="meta">{position.status.toUpperCase()} / {position.round_state.toUpperCase()}</p><h2 className="h2">{position.public_metadata?.title ?? "Research access round"}</h2><p className="body-sm">{Number(position.amount_lamports).toLocaleString("en-US")} lamports · {position.tier.replaceAll("_", " ")}</p>{["settled", "access_granted"].includes(position.round_state) && position.status !== "claimed" && <div className="source-actions" style={{ marginTop: 16 }}><button className="btn btn-primary" disabled={busy} onClick={() => claim(position.round_pda)}>Claim if Top-N</button><button className="btn btn-secondary" disabled={busy} onClick={() => refund(position.round_pda)}>Refund if below Top-N</button></div>}</article>)}{!positions.length && <p className="body-sm">No bids from this wallet yet.</p>}</div></section>}
    <p className="meta" role="status" style={{ marginTop: 22 }}>{notice}</p>
  </main></div>;
}
