-- QARAU auction demo seed - SYNTHETIC DATA, NOT REAL CHAIN STATE.
--
-- Generated by scratchpad/gen_auction_seed.py. Every row it writes carries a
-- demo_seed marker in its jsonb column, so scripts/cleanup-auction-demo.sql can
-- remove all of it again. The PDAs and signatures below are format-valid base58
-- but exist on no cluster: any endpoint that reads them back over RPC (bid,
-- claim, refund, settle) will correctly refuse them. This seeds LISTINGS only.
--
-- Packages and analysis runs hang off real sealed dataset_versions produced by
-- real ingestion, so the provenance chain below the auction layer is genuine.
BEGIN;

-- Buyer wallets
INSERT INTO user_wallets (address, last_authenticated_at) VALUES ('DtyeJLmUAJyG8Nys6sb8ZGux5FHRFAT4Thwf7HMZGwvA', now() - interval '2 hours') ON CONFLICT (address) DO NOTHING; -- Northwind Capital
INSERT INTO user_wallets (address, last_authenticated_at) VALUES ('7HcygJpgy3veBhS9hHWf7xpkKZfpk1qKWjMndhm5QK5d', now() - interval '2 hours') ON CONFLICT (address) DO NOTHING; -- Halden Systematic
INSERT INTO user_wallets (address, last_authenticated_at) VALUES ('8ntxJs72pMvaTT3iEzYdvjWh9BsEiubYAKhehJuAGvKf', now() - interval '2 hours') ON CONFLICT (address) DO NOTHING; -- Orbit Quant
INSERT INTO user_wallets (address, last_authenticated_at) VALUES ('2gweLsgfvA2pFuF7JkdQf2Fk2oLRDyraMni99Aq785e1', now() - interval '2 hours') ON CONFLICT (address) DO NOTHING; -- Vector Delta
INSERT INTO user_wallets (address, last_authenticated_at) VALUES ('BeBN7YwuwQ1ZKem5dwR1xaBywpBwd1e6uGwxdTGMvuRp', now() - interval '2 hours') ON CONFLICT (address) DO NOTHING; -- Meridian Alpha
INSERT INTO user_wallets (address, last_authenticated_at) VALUES ('3nRRpL1eh29G8Th4mJWH1ycFTVzdqvRfoovqNiiKvv9D', now() - interval '2 hours') ON CONFLICT (address) DO NOTHING; -- Basalt Research

-- === Norfolk daily weather / BTC-USD [settled] ===
INSERT INTO dataset_target_mappings (dataset_id, target_id, physical_variable, economic_mechanism, affected_asset, confidence, status, mapping_version, approved_by, approved_at)
VALUES ('558d6ec6-bca7-4021-8585-3cc9e02c259d', '2385eb2b-998d-4aed-a7a9-79ad91c05d7f', 'physical_activity_index', 'Coastal weather severity constrains regional port and logistics throughput.', 'BTC-USD', 0.62, 'approved', 1, '00000000-0000-4000-8000-000000000001', now() - interval '3 days')
ON CONFLICT (dataset_id, target_id, mapping_version) DO NOTHING;
INSERT INTO analysis_runs (id, dataset_version_id, market_snapshot_id, mapping_id, status, pipeline_version, manifest_object_key, manifest_hash, result_object_key, result_hash, report_object_key, started_at, completed_at, alpha_score, score_version, blocking_leakage)
SELECT 'aaaaaaaa-0000-4000-8000-000000000001', '17c4433d-facc-49cc-bd6c-597bdcd3331d', 'cca9c342-e129-4ca0-b20f-f300c4d8a5eb', m.id, 'completed', 'quantitative-v1',
       'analysis/demo1/manifest.json', sha256(convert_to('demo1-manifest','UTF8')),
       'analysis/demo1/results.json',  sha256(convert_to('demo1-result','UTF8')),
       'analysis/demo1/results.json', now() - interval '3 days', now() - interval '3 days' + interval '4 min', 88.4, 'quantitative-v1', false
FROM dataset_target_mappings m WHERE m.dataset_id = '558d6ec6-bca7-4021-8585-3cc9e02c259d' AND m.target_id = '2385eb2b-998d-4aed-a7a9-79ad91c05d7f' AND m.mapping_version = 1
ON CONFLICT (id) DO NOTHING;
INSERT INTO dataset_packages (id, dataset_version_id, analysis_run_id, status, public_metadata, private_metadata_object_key, access_policy, access_policy_object_key, access_policy_hash, max_seats, raw_snapshot_hash, normalized_dataset_hash, analysis_manifest_hash, analysis_result_hash, sealed_at, created_by)
SELECT 'bbbbbbbb-0000-4000-8000-000000000001', '17c4433d-facc-49cc-bd6c-597bdcd3331d', 'aaaaaaaa-0000-4000-8000-000000000001', 'committed',
  jsonb_build_object('demo_seed', true, 'title', 'Norfolk daily weather / BTC-USD', 'description', 'Coastal weather severity constrains regional port and logistics throughput.',
    'coverage', jsonb_build_object('start', v.coverage_start, 'end', v.coverage_end),
    'update_frequency', v.frequency, 'target_asset_class', 'crypto', 'target_symbol', 'BTC-USD',
    'alpha_score_summary', jsonb_build_object('score', 88.4, 'score_version', 'quantitative-v1'),
    'validation_summary', jsonb_build_object('analysis_run_id', 'aaaaaaaa-0000-4000-8000-000000000001')),
  'packages/demo1/private-metadata.json', '{"policy_version":1,"grant_scope":"PURCHASED_DATASET_LINE","allowed_tier_mask":3,"early":{"available_immediately":true},"delayed":{"version_lag":1,"release_seconds":"604800"},"expiry":{"grant_duration_seconds":"2592000"}}'::jsonb, 'packages/demo1/access-policy.json',
  sha256(convert_to('demo1-policy','UTF8')), 6,
  sha256(convert_to('demo1-raw','UTF8')), v.normalized_hash,
  sha256(convert_to('demo1-manifest','UTF8')), sha256(convert_to('demo1-result','UTF8')),
  now() - interval '2 days', '00000000-0000-4000-8000-000000000001'
FROM dataset_versions v WHERE v.id = '17c4433d-facc-49cc-bd6c-597bdcd3331d'
ON CONFLICT (id) DO NOTHING;
INSERT INTO blockchain_commitments (package_id, network, program_id, dataset_pda, transaction_signature, slot, confirmation_status, decoded_account, verified_at, last_reconciled_at)
VALUES ('bbbbbbbb-0000-4000-8000-000000000001', 'devnet', '63VZwKUPcWqo2JwpQHLxT4HHgQsMREpERZg3DpfSnnMw', 'EP7QyRbgDJ5Ah83Q9yZF7GV7W1rwrcVnfNDExyamPU3J', '3TsqxNoxU5J4F6Ktf7ZDoKZyvdgTRWpjiogxnGohFTFVtj5VhrL9HQ8sSGJv7wYNVeMabVQcyFPMUDFDNtLGzfpd', 493900000, 'finalized', jsonb_build_object('demo_seed', true), now() - interval '2 days', now() - interval '2 days')
ON CONFLICT (package_id) DO NOTHING;
INSERT INTO access_rounds (id, package_id, network, program_id, round_pda, opens_at, closes_at, minimum_bid_lamports, max_winners, enabled_tier_mask, settlement_rule, state, bid_count, winners_count, clearing_price_lamports, transaction_signature, slot, confirmation_status, decoded_state, last_reconciled_at)
VALUES ('cccccccc-0000-4000-8000-000000000001', 'bbbbbbbb-0000-4000-8000-000000000001', 'devnet', '63VZwKUPcWqo2JwpQHLxT4HHgQsMREpERZg3DpfSnnMw', 'HHX3YmaC4iXPUzdrVKqquL9htr2y8RXhbqoc1kdWgBzy', now() - interval '5 days', now() - interval '2 days', 2000000, 3, 3, 'top_n_pay_as_bid', 'settled', 5, 3, 5100000, '5LzeMHTMQPYCiu3UcebhQwwK97wpEuUZLUi1gFwPJisFVyWy89bzAPuY9GSQfPdBUpHu2undLKmK8E4mMyEKiDUL', 493901000, 'finalized',
  jsonb_build_object('demo_seed', true, 'bid_count', 5, 'winners_count', 3, 'clearing_price_lamports', 5100000), now())
ON CONFLICT (id) DO NOTHING;
INSERT INTO auction_bids (access_round_id, bid_pda, wallet_id, amount_lamports, tier, status, transaction_signature, observed_slot, placed_at, last_reconciled_at)
SELECT 'cccccccc-0000-4000-8000-000000000001', 'Covrf5Rq8GzZQsP9wcsdxWEpYp45biEdivtHMjTse8BG', w.id, 9400000, 'exclusive_early', 'winner', '5nnpQWtKUTgLaK6CzPpaM746pXe3wyFjzTsorE7ELkttoqrw9vL1uCPvYWshiDbY14GoMrimJo6qjMWBPsieEzPL', 493902000, now() - interval '5 days' + interval '1 hours', now()
FROM user_wallets w WHERE w.address = 'DtyeJLmUAJyG8Nys6sb8ZGux5FHRFAT4Thwf7HMZGwvA' ON CONFLICT (access_round_id, wallet_id) DO NOTHING;
INSERT INTO auction_bids (access_round_id, bid_pda, wallet_id, amount_lamports, tier, status, transaction_signature, observed_slot, placed_at, last_reconciled_at)
SELECT 'cccccccc-0000-4000-8000-000000000001', '1gcwetD1eZHpXCEypuLwRxDNyXwwqB9aCCPVzhpZzEai', w.id, 7250000, 'exclusive_early', 'winner', '1BQHpmjpvXEd1w3sd9DyEyzpLNFEJmvbKiBV6KhPtU8yVumjTJJGS3bedwBMj32vzU2URZSmehctpPsadAVim3Gu', 493902001, now() - interval '5 days' + interval '2 hours', now()
FROM user_wallets w WHERE w.address = '7HcygJpgy3veBhS9hHWf7xpkKZfpk1qKWjMndhm5QK5d' ON CONFLICT (access_round_id, wallet_id) DO NOTHING;
INSERT INTO auction_bids (access_round_id, bid_pda, wallet_id, amount_lamports, tier, status, transaction_signature, observed_slot, placed_at, last_reconciled_at)
SELECT 'cccccccc-0000-4000-8000-000000000001', 'GLsMr87mSUKRsW9rdhQFPwioXcypXwqQThN4GTNQmnC8', w.id, 5100000, 'delayed', 'winner', '4pkzfG2Tf7AvAYVt3smicBXEPymPF6Nnn1z4FCNzYJ8sk3rKcn4dq7Kd5StCxoya3b7fHZLodjA94seA8C7tWrMh', 493902002, now() - interval '5 days' + interval '3 hours', now()
FROM user_wallets w WHERE w.address = '8ntxJs72pMvaTT3iEzYdvjWh9BsEiubYAKhehJuAGvKf' ON CONFLICT (access_round_id, wallet_id) DO NOTHING;
INSERT INTO auction_bids (access_round_id, bid_pda, wallet_id, amount_lamports, tier, status, transaction_signature, observed_slot, placed_at, last_reconciled_at)
SELECT 'cccccccc-0000-4000-8000-000000000001', 'HVuN9A1qPNwgJq31neyqX3iv7oBWdLW5ERhVdEUAKHyB', w.id, 3800000, 'exclusive_early', 'loser', '1c7yGBFMWxEaLpxmSYBsjXd99GbdgYfUuBDR6vQgPFPeX7tKYUszTZLy36asdd1r4nX1humg8KrNcHzHx5vxqgjH', 493902003, now() - interval '5 days' + interval '4 hours', now()
FROM user_wallets w WHERE w.address = '2gweLsgfvA2pFuF7JkdQf2Fk2oLRDyraMni99Aq785e1' ON CONFLICT (access_round_id, wallet_id) DO NOTHING;
INSERT INTO auction_bids (access_round_id, bid_pda, wallet_id, amount_lamports, tier, status, transaction_signature, observed_slot, placed_at, last_reconciled_at)
SELECT 'cccccccc-0000-4000-8000-000000000001', 'B5akq9wzuzygUczfmgxJughZMLJkcFZrH6Eyq54xnERi', w.id, 2400000, 'exclusive_early', 'loser', '4rA5WakULrzJ2Jhzj8vNQC5GE12zdsp99cMcNpeYhDU9essdnSi1WbJuCna3wRfUgzW9wpgyGHbsZB1qWxn5xZTX', 493902004, now() - interval '5 days' + interval '5 hours', now()
FROM user_wallets w WHERE w.address = 'BeBN7YwuwQ1ZKem5dwR1xaBywpBwd1e6uGwxdTGMvuRp' ON CONFLICT (access_round_id, wallet_id) DO NOTHING;
INSERT INTO access_entitlement_cache (entitlement_pda, access_round_id, package_id, wallet_id, tier, bid_amount_lamports, granted_at, expires_at, status, transaction_signature, slot, last_reconciled_at)
SELECT '4HQyAUJgWtTf87rfUQ4z1EX2sUWVDx5voM8b3eE8rJ2X', 'cccccccc-0000-4000-8000-000000000001', 'bbbbbbbb-0000-4000-8000-000000000001', w.id, 'exclusive_early', 9400000, now() - interval '2 days', now() + interval '28 days', 'active', '3o2jsZ9zKCyeLzHonbfFYXvgA83KuWfveSABggt13BqGkdz53LeS7RoQafLe7cEY19dPCJpsYw6pbo1HzcXiJ5Z3', 493903000, now()
FROM user_wallets w WHERE w.address = 'DtyeJLmUAJyG8Nys6sb8ZGux5FHRFAT4Thwf7HMZGwvA' ON CONFLICT (entitlement_pda) DO NOTHING;
INSERT INTO access_entitlement_cache (entitlement_pda, access_round_id, package_id, wallet_id, tier, bid_amount_lamports, granted_at, expires_at, status, transaction_signature, slot, last_reconciled_at)
SELECT '8YuNknmKDt3TSL6XvZWkQagMjzx3HuKTbCqtLdAeDpA2', 'cccccccc-0000-4000-8000-000000000001', 'bbbbbbbb-0000-4000-8000-000000000001', w.id, 'exclusive_early', 7250000, now() - interval '2 days', now() + interval '28 days', 'active', '2xyHD7BaApGhnLBUQFT31Wsk311r84cUswhK42KGmMUyTgU1QATCqAa5BzpSfaPzKMZcBbwxA8F6s4Jnuo16D3mt', 493903001, now()
FROM user_wallets w WHERE w.address = '7HcygJpgy3veBhS9hHWf7xpkKZfpk1qKWjMndhm5QK5d' ON CONFLICT (entitlement_pda) DO NOTHING;
INSERT INTO access_entitlement_cache (entitlement_pda, access_round_id, package_id, wallet_id, tier, bid_amount_lamports, granted_at, expires_at, status, transaction_signature, slot, last_reconciled_at)
SELECT '5PnAqcJRjBk9tf1USi5K1W6gyL4fY1DGYW5vJA2gCF7f', 'cccccccc-0000-4000-8000-000000000001', 'bbbbbbbb-0000-4000-8000-000000000001', w.id, 'delayed', 5100000, now() - interval '2 days', now() + interval '28 days', 'active', '52zWPwhshpvt8ctV3DqaDEu79rN6sM4k5AtnfFQ6jWPo7TiJmdHD5faa5CNiuV7PPRHH1DsYRunPUe1emtpAGcki', 493903002, now()
FROM user_wallets w WHERE w.address = '8ntxJs72pMvaTT3iEzYdvjWh9BsEiubYAKhehJuAGvKf' ON CONFLICT (entitlement_pda) DO NOTHING;
UPDATE auction_bids SET status = 'claimed' WHERE access_round_id = 'cccccccc-0000-4000-8000-000000000001' AND status = 'winner';
UPDATE access_rounds SET state = 'access_granted' WHERE id = 'cccccccc-0000-4000-8000-000000000001';

-- === Calgary traffic incidents / BTC-USD [live] ===
INSERT INTO dataset_target_mappings (dataset_id, target_id, physical_variable, economic_mechanism, affected_asset, confidence, status, mapping_version, approved_by, approved_at)
VALUES ('5291cc7a-8bc9-4662-9818-5e21bdc81afa', '2385eb2b-998d-4aed-a7a9-79ad91c05d7f', 'physical_activity_index', 'Urban traffic incident density proxies regional economic activity intensity.', 'BTC-USD', 0.62, 'approved', 1, '00000000-0000-4000-8000-000000000001', now() - interval '3 days')
ON CONFLICT (dataset_id, target_id, mapping_version) DO NOTHING;
INSERT INTO analysis_runs (id, dataset_version_id, market_snapshot_id, mapping_id, status, pipeline_version, manifest_object_key, manifest_hash, result_object_key, result_hash, report_object_key, started_at, completed_at, alpha_score, score_version, blocking_leakage)
SELECT 'aaaaaaaa-0000-4000-8000-000000000002', '733fb62b-02d6-403b-abc5-8bd896663c25', 'cca9c342-e129-4ca0-b20f-f300c4d8a5eb', m.id, 'completed', 'quantitative-v1',
       'analysis/demo2/manifest.json', sha256(convert_to('demo2-manifest','UTF8')),
       'analysis/demo2/results.json',  sha256(convert_to('demo2-result','UTF8')),
       'analysis/demo2/results.json', now() - interval '3 days', now() - interval '3 days' + interval '4 min', 74.9, 'quantitative-v1', false
FROM dataset_target_mappings m WHERE m.dataset_id = '5291cc7a-8bc9-4662-9818-5e21bdc81afa' AND m.target_id = '2385eb2b-998d-4aed-a7a9-79ad91c05d7f' AND m.mapping_version = 1
ON CONFLICT (id) DO NOTHING;
INSERT INTO dataset_packages (id, dataset_version_id, analysis_run_id, status, public_metadata, private_metadata_object_key, access_policy, access_policy_object_key, access_policy_hash, max_seats, raw_snapshot_hash, normalized_dataset_hash, analysis_manifest_hash, analysis_result_hash, sealed_at, created_by)
SELECT 'bbbbbbbb-0000-4000-8000-000000000002', '733fb62b-02d6-403b-abc5-8bd896663c25', 'aaaaaaaa-0000-4000-8000-000000000002', 'committed',
  jsonb_build_object('demo_seed', true, 'title', 'Calgary traffic incidents / BTC-USD', 'description', 'Urban traffic incident density proxies regional economic activity intensity.',
    'coverage', jsonb_build_object('start', v.coverage_start, 'end', v.coverage_end),
    'update_frequency', v.frequency, 'target_asset_class', 'crypto', 'target_symbol', 'BTC-USD',
    'alpha_score_summary', jsonb_build_object('score', 74.9, 'score_version', 'quantitative-v1'),
    'validation_summary', jsonb_build_object('analysis_run_id', 'aaaaaaaa-0000-4000-8000-000000000002')),
  'packages/demo2/private-metadata.json', '{"policy_version":1,"grant_scope":"PURCHASED_DATASET_LINE","allowed_tier_mask":3,"early":{"available_immediately":true},"delayed":{"version_lag":1,"release_seconds":"604800"},"expiry":{"grant_duration_seconds":"2592000"}}'::jsonb, 'packages/demo2/access-policy.json',
  sha256(convert_to('demo2-policy','UTF8')), 8,
  sha256(convert_to('demo2-raw','UTF8')), v.normalized_hash,
  sha256(convert_to('demo2-manifest','UTF8')), sha256(convert_to('demo2-result','UTF8')),
  now() - interval '2 days', '00000000-0000-4000-8000-000000000001'
FROM dataset_versions v WHERE v.id = '733fb62b-02d6-403b-abc5-8bd896663c25'
ON CONFLICT (id) DO NOTHING;
INSERT INTO blockchain_commitments (package_id, network, program_id, dataset_pda, transaction_signature, slot, confirmation_status, decoded_account, verified_at, last_reconciled_at)
VALUES ('bbbbbbbb-0000-4000-8000-000000000002', 'devnet', '63VZwKUPcWqo2JwpQHLxT4HHgQsMREpERZg3DpfSnnMw', 'Co2UQvG7MnS6oUR24uuFm3e4W4Kh38tYTiZKFmvUnD5E', '1MnVh23x8E5Tz7kX1DdKCh8bp6j8BKEsQn3gsZQ94azBBiRFqEwqryQXdUkN6dxB9RBDBNJrcL7SaRK7joa3EZef', 493901000, 'finalized', jsonb_build_object('demo_seed', true), now() - interval '2 days', now() - interval '2 days')
ON CONFLICT (package_id) DO NOTHING;
INSERT INTO access_rounds (id, package_id, network, program_id, round_pda, opens_at, closes_at, minimum_bid_lamports, max_winners, enabled_tier_mask, settlement_rule, state, bid_count, winners_count, clearing_price_lamports, transaction_signature, slot, confirmation_status, decoded_state, last_reconciled_at)
VALUES ('cccccccc-0000-4000-8000-000000000002', 'bbbbbbbb-0000-4000-8000-000000000002', 'devnet', '63VZwKUPcWqo2JwpQHLxT4HHgQsMREpERZg3DpfSnnMw', '1uosPhgU52UWVzw1sb8yoHXNGrG3PUKuBUwDXtBa39W9', now() - interval '18 hours', now() + interval '30 hours', 1500000, 5, 3, 'top_n_pay_as_bid', 'live', 4, 0, NULL, '5FdQgJAiup15ao5Hyfa99UYXLQiqGUD6uPSKyPuz5CG2axHySkygs76CqSadg9dDKirZtWEvhP6B2Ab96WTV48cr', 493902000, 'finalized',
  jsonb_build_object('demo_seed', true, 'bid_count', 4, 'winners_count', 0, 'clearing_price_lamports', 0), now())
ON CONFLICT (id) DO NOTHING;
INSERT INTO auction_bids (access_round_id, bid_pda, wallet_id, amount_lamports, tier, status, transaction_signature, observed_slot, placed_at, last_reconciled_at)
SELECT 'cccccccc-0000-4000-8000-000000000002', 'AgDBTeEkfpHGy2BeFVt48bb56DTCgQf7eAtoaaSCkk1y', w.id, 6300000, 'exclusive_early', 'active', '2RgkQ3pTvE8gEo5UthMj8pm2YWPwCE5LZKEZoRavgKvgWwkAcT9bitseHXfePzPGdEpHUknwgsBiwUSKUj5h6mNF', 493902100, now() - interval '18 hours' + interval '1 hours', now()
FROM user_wallets w WHERE w.address = 'DtyeJLmUAJyG8Nys6sb8ZGux5FHRFAT4Thwf7HMZGwvA' ON CONFLICT (access_round_id, wallet_id) DO NOTHING;
INSERT INTO auction_bids (access_round_id, bid_pda, wallet_id, amount_lamports, tier, status, transaction_signature, observed_slot, placed_at, last_reconciled_at)
SELECT 'cccccccc-0000-4000-8000-000000000002', '99gKVmP2xiio6rfLYVqujkAjAqjVMgqDUEqTnz939pd2', w.id, 4100000, 'exclusive_early', 'active', '1rGanzdVn9QXu117tKjAPiSaaoNeLESnuvNZEihpZN4Wr6ymhdj1W51wjDuEdNchcJgGpRiF2ZTv35hiUc6WNYV3', 493902101, now() - interval '18 hours' + interval '2 hours', now()
FROM user_wallets w WHERE w.address = '7HcygJpgy3veBhS9hHWf7xpkKZfpk1qKWjMndhm5QK5d' ON CONFLICT (access_round_id, wallet_id) DO NOTHING;
INSERT INTO auction_bids (access_round_id, bid_pda, wallet_id, amount_lamports, tier, status, transaction_signature, observed_slot, placed_at, last_reconciled_at)
SELECT 'cccccccc-0000-4000-8000-000000000002', '644xavPE5PyLnu61NvawxH4dZmbMY7gPx2RBWbkcsZYx', w.id, 2900000, 'delayed', 'active', '3QgUU78Kgkf3J3UKBLu597XfGri6a2Zf7jnoYi19m8occiWLs9D5MFNd9875NcudMxr9FBRtph5CSM5iCQ13KsdB', 493902102, now() - interval '18 hours' + interval '3 hours', now()
FROM user_wallets w WHERE w.address = '8ntxJs72pMvaTT3iEzYdvjWh9BsEiubYAKhehJuAGvKf' ON CONFLICT (access_round_id, wallet_id) DO NOTHING;
INSERT INTO auction_bids (access_round_id, bid_pda, wallet_id, amount_lamports, tier, status, transaction_signature, observed_slot, placed_at, last_reconciled_at)
SELECT 'cccccccc-0000-4000-8000-000000000002', '9sNKnN5sagFMa2CWRP32bj4Sgo1ikPH8eEhB97mZ2KTJ', w.id, 1800000, 'exclusive_early', 'active', '2rzqxFxkHhwJmbuM72LgyU6LfGDpWHPd56bqcucR1BSD6AFWqsvmxFh6CXenqdudkjoiBwSUEmU82bzDmpXwTaBc', 493902103, now() - interval '18 hours' + interval '4 hours', now()
FROM user_wallets w WHERE w.address = '2gweLsgfvA2pFuF7JkdQf2Fk2oLRDyraMni99Aq785e1' ON CONFLICT (access_round_id, wallet_id) DO NOTHING;

-- === Seattle road weather stations / BTC-USD [ended] ===
INSERT INTO dataset_target_mappings (dataset_id, target_id, physical_variable, economic_mechanism, affected_asset, confidence, status, mapping_version, approved_by, approved_at)
VALUES ('ac4cc11c-6267-4de9-9b3a-8c5387ca22dc', '2385eb2b-998d-4aed-a7a9-79ad91c05d7f', 'physical_activity_index', 'Road surface conditions lead freight routing decisions in the Pacific Northwest.', 'BTC-USD', 0.62, 'approved', 1, '00000000-0000-4000-8000-000000000001', now() - interval '3 days')
ON CONFLICT (dataset_id, target_id, mapping_version) DO NOTHING;
INSERT INTO analysis_runs (id, dataset_version_id, market_snapshot_id, mapping_id, status, pipeline_version, manifest_object_key, manifest_hash, result_object_key, result_hash, report_object_key, started_at, completed_at, alpha_score, score_version, blocking_leakage)
SELECT 'aaaaaaaa-0000-4000-8000-000000000003', '5df45721-575b-43f8-adc4-04dc0bbf417c', 'cca9c342-e129-4ca0-b20f-f300c4d8a5eb', m.id, 'completed', 'quantitative-v1',
       'analysis/demo3/manifest.json', sha256(convert_to('demo3-manifest','UTF8')),
       'analysis/demo3/results.json',  sha256(convert_to('demo3-result','UTF8')),
       'analysis/demo3/results.json', now() - interval '3 days', now() - interval '3 days' + interval '4 min', 61.2, 'quantitative-v1', false
FROM dataset_target_mappings m WHERE m.dataset_id = 'ac4cc11c-6267-4de9-9b3a-8c5387ca22dc' AND m.target_id = '2385eb2b-998d-4aed-a7a9-79ad91c05d7f' AND m.mapping_version = 1
ON CONFLICT (id) DO NOTHING;
INSERT INTO dataset_packages (id, dataset_version_id, analysis_run_id, status, public_metadata, private_metadata_object_key, access_policy, access_policy_object_key, access_policy_hash, max_seats, raw_snapshot_hash, normalized_dataset_hash, analysis_manifest_hash, analysis_result_hash, sealed_at, created_by)
SELECT 'bbbbbbbb-0000-4000-8000-000000000003', '5df45721-575b-43f8-adc4-04dc0bbf417c', 'aaaaaaaa-0000-4000-8000-000000000003', 'committed',
  jsonb_build_object('demo_seed', true, 'title', 'Seattle road weather stations / BTC-USD', 'description', 'Road surface conditions lead freight routing decisions in the Pacific Northwest.',
    'coverage', jsonb_build_object('start', v.coverage_start, 'end', v.coverage_end),
    'update_frequency', v.frequency, 'target_asset_class', 'crypto', 'target_symbol', 'BTC-USD',
    'alpha_score_summary', jsonb_build_object('score', 61.2, 'score_version', 'quantitative-v1'),
    'validation_summary', jsonb_build_object('analysis_run_id', 'aaaaaaaa-0000-4000-8000-000000000003')),
  'packages/demo3/private-metadata.json', '{"policy_version":1,"grant_scope":"PURCHASED_DATASET_LINE","allowed_tier_mask":3,"early":{"available_immediately":true},"delayed":{"version_lag":1,"release_seconds":"604800"},"expiry":{"grant_duration_seconds":"2592000"}}'::jsonb, 'packages/demo3/access-policy.json',
  sha256(convert_to('demo3-policy','UTF8')), 5,
  sha256(convert_to('demo3-raw','UTF8')), v.normalized_hash,
  sha256(convert_to('demo3-manifest','UTF8')), sha256(convert_to('demo3-result','UTF8')),
  now() - interval '2 days', '00000000-0000-4000-8000-000000000001'
FROM dataset_versions v WHERE v.id = '5df45721-575b-43f8-adc4-04dc0bbf417c'
ON CONFLICT (id) DO NOTHING;
INSERT INTO blockchain_commitments (package_id, network, program_id, dataset_pda, transaction_signature, slot, confirmation_status, decoded_account, verified_at, last_reconciled_at)
VALUES ('bbbbbbbb-0000-4000-8000-000000000003', 'devnet', '63VZwKUPcWqo2JwpQHLxT4HHgQsMREpERZg3DpfSnnMw', 'CptzzEuCfsfK6EotWu1rjnH3gEY9JGkLTJxsSn3Tz1ym', '5HeQrN5PD4dsiUg6iCbRxPt9BU5kRGbV5xHuJ49cbbrYVSDNMJFTzjev6z2AZNrgWF3qTwJSvwKbbgP1sudkYLqR', 493902000, 'finalized', jsonb_build_object('demo_seed', true), now() - interval '2 days', now() - interval '2 days')
ON CONFLICT (package_id) DO NOTHING;
INSERT INTO access_rounds (id, package_id, network, program_id, round_pda, opens_at, closes_at, minimum_bid_lamports, max_winners, enabled_tier_mask, settlement_rule, state, bid_count, winners_count, clearing_price_lamports, transaction_signature, slot, confirmation_status, decoded_state, last_reconciled_at)
VALUES ('cccccccc-0000-4000-8000-000000000003', 'bbbbbbbb-0000-4000-8000-000000000003', 'devnet', '63VZwKUPcWqo2JwpQHLxT4HHgQsMREpERZg3DpfSnnMw', '4rQsr5KNX4f7hfBTPPJaZUM4iFdMk5rYzhbfsApXbrkf', now() - interval '4 days', now() - interval '6 hours', 3000000, 2, 3, 'top_n_pay_as_bid', 'ended', 3, 0, NULL, '1mN3xzoUo5Hm2oomPmYt3YVm1gqLCK2APqPAk4xx5xbgn77Gmxdvca5GQhWVj8svKfnY8AEzGmJV5D78amtKdKQr', 493903000, 'finalized',
  jsonb_build_object('demo_seed', true, 'bid_count', 3, 'winners_count', 0, 'clearing_price_lamports', 0), now())
ON CONFLICT (id) DO NOTHING;
INSERT INTO auction_bids (access_round_id, bid_pda, wallet_id, amount_lamports, tier, status, transaction_signature, observed_slot, placed_at, last_reconciled_at)
SELECT 'cccccccc-0000-4000-8000-000000000003', '4cWLTJf8zWnd2V295J1tEiYMMRfWQmkZ2u7mFweY6a9x', w.id, 5500000, 'exclusive_early', 'active', '3QiasfpYQF2bVVuGcb7Hsrj1CnyEXcRswai8BEpTVD7wGWFWADEXeUxaaDNbjnYL3tUSu7aeYpfsKAM3VrxV78Cx', 493902200, now() - interval '4 days' + interval '1 hours', now()
FROM user_wallets w WHERE w.address = 'DtyeJLmUAJyG8Nys6sb8ZGux5FHRFAT4Thwf7HMZGwvA' ON CONFLICT (access_round_id, wallet_id) DO NOTHING;
INSERT INTO auction_bids (access_round_id, bid_pda, wallet_id, amount_lamports, tier, status, transaction_signature, observed_slot, placed_at, last_reconciled_at)
SELECT 'cccccccc-0000-4000-8000-000000000003', 'Ep3BKmEB44nLX7fnfM3n2rTGbD3cYmd7EyhdJX8aiB21', w.id, 3300000, 'exclusive_early', 'active', '5RviWdwgzXAbTRaavwA1sHzNrzqmQga4vSZVciwmdCkNtDFyx1wHmAcyJe6rjCcjSwDePBZrZsJSXk98HC25EPuQ', 493902201, now() - interval '4 days' + interval '2 hours', now()
FROM user_wallets w WHERE w.address = '7HcygJpgy3veBhS9hHWf7xpkKZfpk1qKWjMndhm5QK5d' ON CONFLICT (access_round_id, wallet_id) DO NOTHING;
INSERT INTO auction_bids (access_round_id, bid_pda, wallet_id, amount_lamports, tier, status, transaction_signature, observed_slot, placed_at, last_reconciled_at)
SELECT 'cccccccc-0000-4000-8000-000000000003', 'DhcTXVj7tJE5qAeYpbbDUshxC4UcZK1zyQPKf1eCJfze', w.id, 3050000, 'delayed', 'active', '2SUoNv2KoW6eY77sqpctMF1aSKWVCiEsCEeMtcCXGebwUtbtgh3PeCb8ZQH7k1rQeaNCeXwJ2fTzzhKUWHE7Hrih', 493902202, now() - interval '4 days' + interval '3 hours', now()
FROM user_wallets w WHERE w.address = '8ntxJs72pMvaTT3iEzYdvjWh9BsEiubYAKhehJuAGvKf' ON CONFLICT (access_round_id, wallet_id) DO NOTHING;

-- === Calgary traffic cameras / BTC-USD [upcoming] ===
INSERT INTO dataset_target_mappings (dataset_id, target_id, physical_variable, economic_mechanism, affected_asset, confidence, status, mapping_version, approved_by, approved_at)
VALUES ('0b795e4b-9276-4e9e-b0bc-54023414e26b', '2385eb2b-998d-4aed-a7a9-79ad91c05d7f', 'physical_activity_index', 'Camera uptime and coverage proxies municipal infrastructure investment cycles.', 'BTC-USD', 0.62, 'approved', 1, '00000000-0000-4000-8000-000000000001', now() - interval '3 days')
ON CONFLICT (dataset_id, target_id, mapping_version) DO NOTHING;
INSERT INTO analysis_runs (id, dataset_version_id, market_snapshot_id, mapping_id, status, pipeline_version, manifest_object_key, manifest_hash, result_object_key, result_hash, report_object_key, started_at, completed_at, alpha_score, score_version, blocking_leakage)
SELECT 'aaaaaaaa-0000-4000-8000-000000000004', '65db7d3d-26f0-4301-9c6a-5f4b7796bb27', 'cca9c342-e129-4ca0-b20f-f300c4d8a5eb', m.id, 'completed', 'quantitative-v1',
       'analysis/demo4/manifest.json', sha256(convert_to('demo4-manifest','UTF8')),
       'analysis/demo4/results.json',  sha256(convert_to('demo4-result','UTF8')),
       'analysis/demo4/results.json', now() - interval '3 days', now() - interval '3 days' + interval '4 min', 52.7, 'quantitative-v1', false
FROM dataset_target_mappings m WHERE m.dataset_id = '0b795e4b-9276-4e9e-b0bc-54023414e26b' AND m.target_id = '2385eb2b-998d-4aed-a7a9-79ad91c05d7f' AND m.mapping_version = 1
ON CONFLICT (id) DO NOTHING;
INSERT INTO dataset_packages (id, dataset_version_id, analysis_run_id, status, public_metadata, private_metadata_object_key, access_policy, access_policy_object_key, access_policy_hash, max_seats, raw_snapshot_hash, normalized_dataset_hash, analysis_manifest_hash, analysis_result_hash, sealed_at, created_by)
SELECT 'bbbbbbbb-0000-4000-8000-000000000004', '65db7d3d-26f0-4301-9c6a-5f4b7796bb27', 'aaaaaaaa-0000-4000-8000-000000000004', 'committed',
  jsonb_build_object('demo_seed', true, 'title', 'Calgary traffic cameras / BTC-USD', 'description', 'Camera uptime and coverage proxies municipal infrastructure investment cycles.',
    'coverage', jsonb_build_object('start', v.coverage_start, 'end', v.coverage_end),
    'update_frequency', v.frequency, 'target_asset_class', 'crypto', 'target_symbol', 'BTC-USD',
    'alpha_score_summary', jsonb_build_object('score', 52.7, 'score_version', 'quantitative-v1'),
    'validation_summary', jsonb_build_object('analysis_run_id', 'aaaaaaaa-0000-4000-8000-000000000004')),
  'packages/demo4/private-metadata.json', '{"policy_version":1,"grant_scope":"PURCHASED_DATASET_LINE","allowed_tier_mask":3,"early":{"available_immediately":true},"delayed":{"version_lag":1,"release_seconds":"604800"},"expiry":{"grant_duration_seconds":"2592000"}}'::jsonb, 'packages/demo4/access-policy.json',
  sha256(convert_to('demo4-policy','UTF8')), 7,
  sha256(convert_to('demo4-raw','UTF8')), v.normalized_hash,
  sha256(convert_to('demo4-manifest','UTF8')), sha256(convert_to('demo4-result','UTF8')),
  now() - interval '2 days', '00000000-0000-4000-8000-000000000001'
FROM dataset_versions v WHERE v.id = '65db7d3d-26f0-4301-9c6a-5f4b7796bb27'
ON CONFLICT (id) DO NOTHING;
INSERT INTO blockchain_commitments (package_id, network, program_id, dataset_pda, transaction_signature, slot, confirmation_status, decoded_account, verified_at, last_reconciled_at)
VALUES ('bbbbbbbb-0000-4000-8000-000000000004', 'devnet', '63VZwKUPcWqo2JwpQHLxT4HHgQsMREpERZg3DpfSnnMw', 'HWBbQo2SznxCeda8kLKscPKhgbgZaeb2UL25DPo9Stma', '1jriuBYcHNyRzaDWZX83AMWUzFLkqDKBGNdwXEz3jEFEsRBy2L89T89mcTzytYheDDW9fJps6Jpnfwwb6UDbvj8t', 493903000, 'finalized', jsonb_build_object('demo_seed', true), now() - interval '2 days', now() - interval '2 days')
ON CONFLICT (package_id) DO NOTHING;
INSERT INTO access_rounds (id, package_id, network, program_id, round_pda, opens_at, closes_at, minimum_bid_lamports, max_winners, enabled_tier_mask, settlement_rule, state, bid_count, winners_count, clearing_price_lamports, transaction_signature, slot, confirmation_status, decoded_state, last_reconciled_at)
VALUES ('cccccccc-0000-4000-8000-000000000004', 'bbbbbbbb-0000-4000-8000-000000000004', 'devnet', '63VZwKUPcWqo2JwpQHLxT4HHgQsMREpERZg3DpfSnnMw', 'CxLiqLbCU22aVb2QqnjgvYmDNho7ufe9qsTfVNBTd4Fz', now() + interval '2 days', now() + interval '6 days', 1000000, 4, 3, 'top_n_pay_as_bid', 'upcoming', 0, 0, NULL, '5KNUTx2xA5B8ZtGvZuULC5eCTP1GXiM2rqUYVA4pV59tji9ahb5NnsgSx6nrtDHdHhMts4EJqNY41bpJCad7nzgc', 493904000, 'finalized',
  jsonb_build_object('demo_seed', true, 'bid_count', 0, 'winners_count', 0, 'clearing_price_lamports', 0), now())
ON CONFLICT (id) DO NOTHING;

-- The one genuinely committed package needs a round or the marketplace hides it.
INSERT INTO access_rounds (package_id, network, program_id, round_pda, opens_at, closes_at, minimum_bid_lamports, max_winners, enabled_tier_mask, settlement_rule, state, bid_count, winners_count, transaction_signature, slot, confirmation_status, decoded_state, last_reconciled_at)
VALUES ('281d1ccf-dad7-4346-a1df-8d3516fe3c7e', 'devnet', '63VZwKUPcWqo2JwpQHLxT4HHgQsMREpERZg3DpfSnnMw', 'DnXh8zR6Cm4M4vkm4zMYJ6b1teRv4KXQQDNXixaayvSo', now() - interval '6 hours', now() + interval '42 hours', 1000000, 5, 3, 'top_n_pay_as_bid', 'live', 2, 0, '1roi5vaAjQjB8RhGriMvo41aTCSrrmzM4dpVpvrAMW2291qz8SVUu7GL6WUsKY5CP4v9Y2GQCNS6ZDqR1Moe8Jjp', 493905000, 'finalized',
  jsonb_build_object('demo_seed', true, 'bid_count', 2, 'winners_count', 0), now())
ON CONFLICT (package_id) DO NOTHING;
INSERT INTO auction_bids (access_round_id, bid_pda, wallet_id, amount_lamports, tier, status, transaction_signature, observed_slot, placed_at, last_reconciled_at)
SELECT r.id, 'CxNJgFMZ5cvTbubst3xVpjs6dGTVUvKxkS8t4P7LdB8s', w.id, 4500000, 'exclusive_early', 'active', '4y6qBmXMo1BBmw3Cu8AwqqFU3VwwtqtKdg34djmamNKxYgeBmpCGWZ94W9KY7N3iDSAdmGVDvSYqbFpJjmNWHaRh', 493906000, now() - interval '2 hours', now()
FROM access_rounds r, user_wallets w WHERE r.package_id = '281d1ccf-dad7-4346-a1df-8d3516fe3c7e' AND w.address = 'BeBN7YwuwQ1ZKem5dwR1xaBywpBwd1e6uGwxdTGMvuRp' ON CONFLICT (access_round_id, wallet_id) DO NOTHING;
INSERT INTO auction_bids (access_round_id, bid_pda, wallet_id, amount_lamports, tier, status, transaction_signature, observed_slot, placed_at, last_reconciled_at)
SELECT r.id, 'AwZAtKudytFAhMH89jYzKnwQm7E76ao11VigAPj6WcFg', w.id, 3300000, 'delayed', 'active', '1YT6Y6WXGvzDAd7ZKFvsH7Ua6LKoeEgg1Sz62Ho7B4DP8CMdtN1GHBUYtJfsqg2Bdx11BASidV2mwzk68kx9idxb', 493906001, now() - interval '3 hours', now()
FROM access_rounds r, user_wallets w WHERE r.package_id = '281d1ccf-dad7-4346-a1df-8d3516fe3c7e' AND w.address = '3nRRpL1eh29G8Th4mJWH1ycFTVzdqvRfoovqNiiKvv9D' ON CONFLICT (access_round_id, wallet_id) DO NOTHING;

COMMIT;
